_wandb:
    value:
        cli_version: 0.23.0
        e:
            k3ukxy1yylpzr2tg5k6cnlwg0rj269zd:
                args:
                    - --params
                    - datalists/SEM/train.json
                codePath: train_adapted.py
                codePathLocal: train_adapted.py
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "527292432384"
                        used: "70932258816"
                email: luca.klem@web.de
                executable: /home/klem/Documents/struct-uncertainty/.venv/bin/python
                git:
                    commit: 5744fb184648ea2982d5a7aa5b098290fe41999f
                    remote: https://github.com/Lugga19/struct-uncertainty.git
                gpu: NVIDIA A16
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 1280
                      memoryTotal: "16101933056"
                      name: NVIDIA A16
                      uuid: GPU-6c3d8f33-6e9f-5712-c46f-28845cd701ba
                    - architecture: Ampere
                      cudaCores: 1280
                      memoryTotal: "16101933056"
                      name: NVIDIA A16
                      uuid: GPU-f1f29bc7-5d75-50f6-384b-e0664e5baeab
                host: dmz-ub24-01
                memory:
                    total: "50509623296"
                os: Linux-6.14.0-35-generic-x86_64-with-glibc2.39
                program: /home/klem/Documents/struct-uncertainty/train_adapted.py
                python: CPython 3.12.3
                root: /home/klem/Documents/struct-uncertainty
                startedAt: "2025-11-24T14:42:17.917603Z"
                writerId: k3ukxy1yylpzr2tg5k6cnlwg0rj269zd
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 51
                - 77
            "2":
                - 1
                - 41
                - 51
                - 77
            "3":
                - 16
            "4": 3.12.3
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
dataname:
    value: SEM
folders:
    value:
        - ""
        - ""
learning_rate:
    value: 0.001
network:
    value: edgedetector
num_classes:
    value: 1
num_epochs:
    value: 11
output_folder:
    value: ./output
save_every:
    value: 10
segmodel_checkpoint_restore:
    value: /home/klem/Documents/struct-uncertainty/edgedetector/weights/default_model.pth
train_datalist:
    value: /home/klem/Documents/training_data_sharper_edges/training/training.lst
training_folder:
    value: /home/klem/Documents/training_data_sharper_edges/training
val_folder:
    value: /home/klem/Documents/training_data_sharper_edges/validation
validation_datalist:
    value: /home/klem/Documents/training_data_sharper_edges/validation/validation.lst
